### ISSUE TITLE
Netlify Deployment Issue

### ISSUE THREAD

**Issue by sramesh2002** [blues/sparrow-reference-web-app#124]
Hello,

I am currently in the process of trying to deploy my modified version of the web app onto Netlify. I see these following errors and these errors seem to not be mentioned anywhere on Confluence or in the README files, so I was wondering if there is something I can do to fix this issue.
![image](https://user-images.githubusercontent.com/71660639/231846301-4c737574-0551-45f3-b65f-1deafb9e7d38.png)

**Comment by sramesh2002** [comment]
Yeah, all the variables are on the .env file. It works on the Docker container, and I just cloned that repository for netlify, so I was sure it would work on Netlify.

**Comment by paigen11** [comment]
The `.env` file isn't what Netlify reads environment variables and secrets from. You actually have to set those variables inside of your Netlify project via the "Site Settings" tab (see my screenshot that shows the variables set inside of the Netlify platform).

If you haven't already, try reading through our ["Deploy on Netlify"](https://bluesinc.atlassian.net/wiki/spaces/SPAR/pages/4686203/Deploy+Sparrow+Reference+Web+App+with+Netlify) guide for more details.

![Screenshot 2023-04-13 at 5 22 39 PM](https://user-images.githubusercontent.com/20400845/231886411-1dc91bb9-6eff-4d55-ab91-0bd6f7383616.png)

**Comment by sramesh2002** [comment]
![image](https://user-images.githubusercontent.com/71660639/231917101-f5ee4eb7-53ea-4ef5-bb8a-4f47d2f5747b.png)

These are all I have in there, so do I just need to add DATABASE_URL and DEBUG_CONFIG?

**Comment by paigen11** [comment]
You'll also need to include `DATABASE_URL`.

`DEBUG_CONFIG` is an optional value we included for better logging in case the app encounters errors, but it's not required.

**Comment by sramesh2002** [comment]
Hi Paige,

So, I included the DATABASE_URL as an environment variable, and now I am getting a different issue.

![image](https://user-images.githubusercontent.com/71660639/232091490-57b012cf-dfec-4a26-aa76-d1d17302e4da.png)

It says that my database is not up and running, so I thought I had to open up my Docker Container to re-open the database and let it run. That still did not fix the issue. Any guidance on this would be great!

Thank you for being patient with me!

**Comment by paigen11** [comment]
Hi Sreedhar, 

Unfortunately you can't point a hosted Netlify site towards a locally running database on your local machine. You'll need to look into hosting your database somewhere like Amazon Web Services or another cloud database platform.

I'd recommend looking at this documentation from Prisma for choosing the database configuration that will work best for your needs: https://www.prisma.io/dataguide/postgresql/5-ways-to-host-postgresql

**Comment by sramesh2002** [comment]
Hi Paige,

Thank you for the clarification!
