### ISSUE TITLE
Chart date range only shows last 24 hours regardless of selection

### ISSUE THREAD

**Issue by zfields** [blues/sparrow-reference-web-app#93]
![image](https://user-images.githubusercontent.com/2801887/167848503-94223892-7679-44c0-b5f2-d1d290d32f91.png)

This is also visible from the logs produced by the page...

```
Extracted 318 Events from Notehub. Done
Extracted 100 Events from Notehub through 2022-05-10T20:01:59Z...
Extracted 150 Events from Notehub through 2022-05-10T23:15:59Z...
Extracted 200 Events from Notehub through 2022-05-11T03:25:54Z...
Extracted 250 Events from Notehub through 2022-05-11T07:23:55Z...
Extracted 300 Events from Notehub through 2022-05-11T10:47:25Z...
Extracted 318 Events from Notehub. Done
```

**Comment by zfields** [comment]
My Sparrow network has been running since last week, so this was unexpected.

I went to Notehub to confirm, but I ran into the following:

![image](https://user-images.githubusercontent.com/2801887/167858916-30661867-be43-4b8f-98fc-08f9ce59defb.png)

I have a feeling the data available to the Sparrow Reference Web App is related to the "plan" our customers are using. That being said, this is probably the "most likely" path that our beta testers and new customers will encounter, so we really should do something in the UI to indicate as much.

**Comment by paigen11** [comment]
Ah! I see. Did you swap over to the new Sparrow demo project TJ created on Friday, or are you running on another Notehub 
project?

**Comment by zfields** [comment]
After upgrading my plan, I was able to see information from the previous days.

![image](https://user-images.githubusercontent.com/2801887/167914324-f3b63a55-f4a1-41e8-844e-83bd820f6629.png)

I can confirm, the drop down works as expected. It would be awesome if it didn't give the option to see the days that it won't show, but at least it does work correctly. :+1:
