### ISSUE TITLE
Charts would be easier to read with 24hr time or AM, PM

### ISSUE THREAD

**Issue by zfields** [blues/sparrow-reference-web-app#94]
![image](https://user-images.githubusercontent.com/2801887/167848994-77b9512f-8ab1-4d58-bef7-769f28312cc8.png)

**Comment by paigen11** [comment]
Would you prefer uppercase or lowercase AM / PM?

**Comment by zfields** [comment]
No great preference, but upper seems "normal" to me.

**Comment by paigen11** [comment]
Can do. Thanks!

**Comment by paigen11** [comment]
This issue is fixed in PR: https://github.com/blues/sparrow-reference-web-app/pull/96
