### ISSUE TITLE
Incorrect day number on motion card date value

### ISSUE THREAD

**Issue by zfields** [blues/sparrow-reference-web-app#99]
![image](https://user-images.githubusercontent.com/2801887/168588171-b1534ed2-1e46-401e-9fc0-2f0898fcb2ce.png)

You can see the card above (Voltage), and indeed all other cards, span from the 15th to 16th, whereas the Motion card repeats the 15th.

**Comment by paigen11** [comment]
Thanks for bringing this up - upon further inspection it looks like times weren't being repeated but the lacked AM/PM markers, and that there were only a few motion events that happened in the time period specified (unlike temp or voltage, which reports in on regular intervals), which caused this confusion when viewing the chart.

I'd encourage you to try this out again with our latest code changes to repo and please reopen the issue if it persists.
